[package]
name = "archipel-file-carrier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.2"
ud3tn_aap = {git = "git@github.com:EpicKiwi/rust-ud3tn.git"}